export const sampler = [
  { label: 'Euler a', val: 'Euler a' },
  { label: 'Euler', val: 'Euler' },
  { label: 'LMS', val: 'LMS' },
  { label: 'Heun', val: 'Heun' },
  { label: 'DPM2', val: 'DPM2' },
  { label: 'DPM2 a', val: 'DPM2 a' },
  { label: 'DPM++ 2S a', val: 'DPM++ 2S a' },
  { label: 'DPM++ 2M', val: 'DPM++ 2M' },
  { label: 'DPM++ SDE', val: 'DPM++ SDE' },
  { label: 'DPM fast', val: 'DPM fast' },
  { label: 'DPM adaptive', val: 'DPM adaptive' },
  { label: 'LMS Karras', val: 'LMS Karras' },
  { label: 'DPM2 Karras', val: 'DPM2 Karras' },
  { label: 'DPM2 a Karras', val: 'DPM2 a Karras' },
  { label: 'DPM++ 2S a Karras', val: 'DPM++ 2S a Karras' },
  { label: 'DPM++ 2M Karras', val: 'DPM++ 2M Karras' },
  { label: 'DPM++ SDE Karras', val: 'DPM++ SDE Karras' },
  { label: 'DDIM', val: 'DDIM' },
  { label: 'PLMS', val: 'PLMS' },
  { label: 'UniPC', val: 'UniPC' },
];
